name: Manual Trigger with URLs and Mode

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'url逗号分隔'
        required: true
        type: string
      tags:
        description: '保存为'
        required: false
        type: string
        default: ''
      skipQueryParams:
        description: '跳过查询参数'
        required: false
        type: boolean
        default: true

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          tags: tag:ci
          authkey: ${{secrets.TS_KEY}}
          args: ${{vars.TS_ADD_ARGS}}
          hostname: github-ci-crawl
          ping: lan-server.chloc

      - uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - run: npm i

      - run: npm start
        env:
          INPUT_URL: ${{github.event.inputs.url}}
          INPUT_TAGS: ${{github.event.inputs.tags}}
          skipQueryParams: ${{github.event.inputs.skipQueryParams}}
      - name: 上传文档
        uses: wszgrcy/upload-s3-action@2.0.7
        with:
          mode: upload
          aws_key_id: ${{secrets.S3_ID}}
          aws_secret_access_key: ${{secrets.S3_KEY}}
          endpoint: ${{secrets.S3_ENDPOINT}}
          aws_bucket: "auto-docs"
          source_dir: 'output/*/*'
          destination_dir: "./"